"""add_lists_list_items_ref_counters_tables

Revision ID: 1653e4ff49b1
Revises: 8a3c2d1e4f5b
Create Date: 2026-06-11 22:17:50.245084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1653e4ff49b1"
down_revision: str | Sequence[str] | None = "8a3c2d1e4f5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ref_counters",
        sa.Column(
            "owner_context",
            sa.String(length=50),
            nullable=False,
            comment="Context key, e.g. 'personal'",
        ),
        sa.Column(
            "owner_user_id",
            sa.Uuid(),
            nullable=True,
            comment="FK → users.id (future constraint)",
        ),
        sa.Column(
            "group_id", sa.Uuid(), nullable=True, comment="Group scope — unused in v0.1"
        ),
        sa.Column(
            "object_type",
            sa.String(length=50),
            nullable=False,
            comment="Module slug, e.g. 'lists'",
        ),
        sa.Column(
            "next_value",
            sa.Integer(),
            nullable=False,
            comment="Next ref_no to allocate",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_context",
            "owner_user_id",
            "group_id",
            "object_type",
            name="uq_ref_counters_scope",
        ),
    )
    op.create_table(
        "lists",
        sa.Column(
            "ref_no",
            sa.Integer(),
            nullable=False,
            comment="Human-readable ref_no — {LIST:ref_no}",
        ),
        sa.Column(
            "owner_context", sa.String(length=50), nullable=False, comment="Scope key"
        ),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False, comment="FK → users.id"),
        sa.Column(
            "group_id", sa.Uuid(), nullable=True, comment="Group scope — unused in v0.1"
        ),
        sa.Column("title", sa.String(length=500), nullable=False, comment="List title"),
        sa.Column(
            "icon", sa.String(length=100), nullable=True, comment="Icon name/emoji"
        ),
        sa.Column(
            "list_type",
            sa.String(length=20),
            nullable=False,
            comment="tasks | checklist | ideas | custom",
        ),
        sa.Column(
            "field_schema",
            sa.JSON(),
            nullable=False,
            comment="Custom field definitions",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_context", "owner_user_id", "ref_no", name="uq_lists_owner_ref"
        ),
    )
    op.create_index(
        "ix_lists_owner_context_user",
        "lists",
        ["owner_context", "owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lists_owner_user_id"), "lists", ["owner_user_id"], unique=False
    )
    op.create_index("ix_lists_title", "lists", ["title"], unique=False)
    op.create_table(
        "list_items",
        sa.Column("list_id", sa.Uuid(), nullable=False, comment="FK → lists.id"),
        sa.Column(
            "title",
            sa.Text(),
            nullable=False,
            comment="Raw title — may contain tag markup",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Raw description — may contain tag markup",
        ),
        sa.Column("is_done", sa.Boolean(), nullable=False, comment="Completion status"),
        sa.Column(
            "priority",
            sa.SmallInteger(),
            nullable=True,
            comment="User priority (lower = more urgent)",
        ),
        sa.Column(
            "due_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Due date in UTC",
        ),
        sa.Column(
            "notify_before",
            sa.Integer(),
            nullable=True,
            comment="Seconds before due_at to notify",
        ),
        sa.Column(
            "assignee_user_id",
            sa.Uuid(),
            nullable=True,
            comment="Assignee — unused in v0.1",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Sort position within list",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["list_id"], ["lists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_list_items_list_id"), "list_items", ["list_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_list_items_list_id"), table_name="list_items")
    op.drop_table("list_items")
    op.drop_index("ix_lists_title", table_name="lists")
    op.drop_index(op.f("ix_lists_owner_user_id"), table_name="lists")
    op.drop_index("ix_lists_owner_context_user", table_name="lists")
    op.drop_table("lists")
    op.drop_table("ref_counters")
    # ### end Alembic commands ###
