"""create modules table

Revision ID: 25b253532399
Revises:
Create Date: 2026-06-07 08:12:08.518422

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25b253532399"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column(
            "key",
            sa.String(length=64),
            nullable=False,
            comment="Unique module key (e.g. 'lists')",
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "enabled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC timestamp of last enable",
        ),
        sa.Column(
            "enabled_by",
            sa.String(length=255),
            nullable=True,
            comment="Identifier of the admin who enabled it",
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modules")
    # ### end Alembic commands ###
